name: social_media_app_using_firebase
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.12
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.0.17
  flutter_facebook_auth: ^7.1.5
  get_it: ^9.2.0
  google_sign_in: ^7.2.0
  image_picker: ^1.2.1
  injectable: ^2.7.1+4
  uuid: ^4.5.2
  http: ^1.6.0
  pinput: ^6.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  injectable_generator: ^2.9.1
  build_runner: ^2.11.0
  flutter_lints: ^5.0.0
  flutter_test:   
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Public Path app icon.png"

flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
  - family: InstagramSans
    fonts:
      - asset: assets/font1/Instagram Sans.ttf
      - asset: assets/font1/Instagram Sans Bold.ttf
        weight: 700
      - asset: assets/font1/Instagram Sans Medium.ttf
        weight: 500
      - asset: assets/font1/Instagram Sans Light.ttf
        weight: 300   
      - asset: assets/font1/Instagram Sans Headline.otf
        weight: 800   

